//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using UnityEngine;
    
    
    [System.Serializable()]
    public  class ItemObj
    {
        
        public uint itemId;
        
        public string itemName;
        
        public uint itemPrice;
    }
}
